### ISSUE TITLE
[tracking] Media Type improvements

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/http-types#274]
This is a tracking issue for a variety of improvements to how we handle media types in `http-types`:

- [ ] Rename `Mime` to `MediaType (semver major) ` #251
- [ ] Add `Mime::into_extension` #271
- [ ] Port mime-db to Rust to enhance our mime extension guessing #272
- [ ] Add `Mime::is_compressible` method #273
